[2단계 - 계산기] 준찌(장준혁) 미션 제출합니다.
woowacourse/react-calculator pull request #54
Opened 2022-04-24 14:02 UTC by juunzzi

2022-04-26 06:00 UTC, austinpark420 requested changes
안녕하세요 준찌 😄 
날씨가 금방 더워지네요. 그나마 아직까지는 바람이 선선하게 불어서 다행인것 같습니다.

작성해주신 코드에 코멘트 달았습니다.
PR에 데모페이지가 없어 로컬에서 페이지를 띄어서 보려고 했는데 이슈가 있어서 이 부분은 수정된 후에 머지를 해야할 것 같아 Request changes으로 진행할게요.
수정하시고 다시 리뷰 요청주시면 그 때 머지하도록 하겠습니다!

2022-04-26 06:00 UTC, austinpark420 commented on src/components/Calculator.jsx
> +  }
switch 문으로 변경 해도 괜찮을것 같습니다.ㅎ

2022-04-26 06:00 UTC, austinpark420 commented on src/components/Calculator.jsx
> +  } = useMemo(() => JSON.parse(localStorage.getItem('prevState')), []);
useMemo를 사용하신 이유를 알 수 있을까요?

2022-04-26 06:00 UTC, austinpark420 commented on src/components/Calculator.jsx
> +  const [isError, setIsError] = useState(prevIsError ?? DEFAULT_VALUE.isError);
연관된 것들끼리는 하나의 state으로 관리해도 좋을것 같습니다.

2022-04-26 06:00 UTC, austinpark420 commented on src/components/Calculator.jsx
> +  };
onClickDigit 함수 하나가 많은 일을 하고 있는것 같아요. 가능하면 좀 더 작은 단위로 리팩토링해봐도 좋을것 같습니다.

2022-04-26 06:00 UTC, austinpark420 commented on src/components/Calculator.jsx
> +import { useEffect, useMemo, useState } from 'react';
다음 미션때는 컴포넌트를 분리해서 작업해보시면 좋을 것 같습니다 😄

2022-04-26 06:00 UTC, austinpark420 commented on src/components/Calculator.jsx
> +  } = useMemo(() => JSON.parse(localStorage.getItem('prevState')), []);
JSON.parse(localStorage.getItem('prevState')) 값이 없을 때, 디스트럭쳐링을 하게되면 어떻게 될까요?

2022-04-26 06:00 UTC, austinpark420 commented on src/components/Calculator.jsx
> +  } = useMemo(() => JSON.parse(localStorage.getItem('prevState')), []);
데모페이지가 없어 로컬로 구동했을 때, 이 부분 때문에 에러가 나네요 😢

2022-04-26 06:00 UTC, austinpark420 commented on src/components/Calculator.jsx
> +        <div className="digits flex">
계산기 digits의 순서가 역방향으로 나오고 있습니다. css 수정이 필요해 보입니다 😢 

![Screen Shot 2022-04-26 at 2 52 37 PM](https://user-images.githubusercontent.com/35208965/165230943-28c86ad2-8081-4839-9b34-186014186708.png)

2022-04-29 01:29 UTC, austinpark420 approved these changes

2022-04-29 01:29 UTC, merged

2022-05-03 11:53 UTC, juunzzi commented on src/components/Calculator.jsx
> +  }
ㅜㅜㅜㅜㅜ 다음 단계 미션 진행하다가 이제서야 봤네요 리뷰 감사합니다

2022-05-03 11:57 UTC, juunzzi commented on src/components/Calculator.jsx
> +  } = useMemo(() => JSON.parse(localStorage.getItem('prevState')), []);
useMemo는 마운트 시 로컬스토리지에서 상태값을 뽑아오기위해 사용해봤어요 `JSON.parse(localStorage.getItem('prevState'))` 같은 작업을 렌더링 마다 할 필요는 없고 첫 컴포넌트 로드시에만 해주면된다고 생각해서 그랬습니다.

**근데 생각해보니 컴포넌트 스코프에 놔둘게 아니라 해당 파일의 모듈 스코프에 놔두면 될 일 인 것 같네요 !!**

데모 페이지는 정말 죄송합니다. ㅠㅠ.. 이번 미션이 연습미션이라 좀 소홀하게 생각했나봐요..다음 단계 미션도 너무 힘들어서 흑

리뷰어님의 시간을 뺏어 죄송합니다.

2022-05-03 11:58 UTC, juunzzi commented on src/components/Calculator.jsx
> +  const [isError, setIsError] = useState(prevIsError ?? DEFAULT_VALUE.isError);
리뷰 감사합니다