[2단계 - 계산기] 밧드(감우영) 미션 제출합니다.
woowacourse/react-calculator pull request #58
Opened 2022-04-24 16:23 UTC by kamwoo

2022-04-25 15:19 UTC, HyeonaKwon requested changes
밧드 안녕하세요! 금방 2단계 제출해주셨군요!

피드백은 코멘트로 남겼으니 확인 부탁드립니다~
질문과 관련해서! state 를 하나하나 풀어놓는 것과 묶어놓는 것은 상황에 따라 취향에 따라 맞게 골라써도 좋은데요, 지금 현 상황에서는 state 라고 변수명을 설정한게 조금 아쉽습니다. 무슨 state 가 저장되는건지 다 찾아봐야하죠!
그리고 컴포넌트의 props 이름들 또한 state 와 setState 로 설정하셨는데요, 사용처에서는 해당 컴포넌트가 어떤 정보를 넘겨받고 싶은건지 알 수가 없습니다 🥲 지금과 같이 타입스크립트를 적용하지 않았을 때는 더더욱 알기가 어려워 컴포넌트 구현부까지 들어가봐야해요! 요 부분 개선해봤으면 좋겠습니다~

2022-04-25 15:19 UTC, HyeonaKwon commented on package.json
> +    "prettier": "^2.6.2"
👍

2022-04-25 15:19 UTC, HyeonaKwon commented on src/components/AllClearButton.js
> +    setState(CALCULATOR_INITIAL_STATE);
오.. setState 라고 props 명을 받아오는건 좋지 않아보입니다! 지금이야 코드가 짧아서 `props 구나` 하지만 AllClearButton 이 커진다면 `AllClearButton 의 state 를 바꾸는구나!` 라고 생각할 것 같아요.
props 명은 사용처를 위해서도, 구현처를 위해서도 명시적으로 정하는게 좋을 것 같아요! 예를 들면 clear 라고 받아오면 어떨까요? 
setState 함수를 하나고 여러 컴포넌트에서 사용한다고 해서 여러 컴포넌트의 props 이름이 다 똑같아야하는건 아닙니당!

```javascript
//부모컴포넌트
function App () {
  const setState = () => {};

  return (
    <>
      <div className="modifiers subgrid">
        <AllClearButton clear={setState} />
      </div>
      <div className="operations subgrid">
        {OPERATOR_LIST.map((operand, index) => (
          <OperatorButton
            ...
            updateOperator={setState}
          />
        ))}
      </div>
      </>
  );
}
```

2022-04-25 15:19 UTC, HyeonaKwon commented on src/components/Calculator.js
> +    }));
결국 state 를 모두 업데이트하고 있는 것 같은데요, prevState 를 사용하는 이유가 있나요?

```suggestion
    setState({ sum, prevNumbers, operator, nextNumbers });
```

2022-04-25 15:19 UTC, HyeonaKwon commented on src/components/Calculator.js
> +  });
useEffect 의 두번째 인자에 값을 넘겼을 때와 넘기지 않았을 때 다른 점은 무엇일까요?

2022-04-25 15:19 UTC, HyeonaKwon commented on src/components/Calculator.js
> +  }, []);
confirmExist 는 useEffect 에서 사용하는 것으로 보이는데요, 순서를 바꿔보는건 어떨까요?

```javascript
const Calculator = () => {
  // state, ref 선언부
  ...

  // 함수들
  const confirmExist = ...;
  const setInitialState = ...;

  // useEffect 들
  useEffect(() => {}, [...]);
  useEffect(() => {}, [...]);

  return ();
}
```

2022-04-25 15:19 UTC, HyeonaKwon commented on src/components/Calculator.js
> +              number={-(index - 9)}
```suggestion
              number={9 - index}
```

2022-04-25 15:19 UTC, HyeonaKwon commented on src/components/OperatorButton.js
> +  };
요게 연산자버튼이 갖고 있어야하는게 맞나 싶네요! 그냥 `어떤 버튼이 눌렸어!` 를 부모한테 알려주면 부모가 계산하는건 어떨까 싶기도 합니다!

2022-04-25 16:10 UTC, kamwoo commented on src/components/Calculator.js
> +              number={-(index - 9)}
감사합니다🙂

2022-04-25 16:15 UTC, kamwoo commented on src/components/Calculator.js
> +    }));
이전에 local storage에 저장이 안돼서 이것저것 다 해보다가 넘어갔었고 수정했습니다.

2022-04-25 16:18 UTC, kamwoo commented on src/components/Calculator.js
> +  });
두번째 인자를 주지 않으면 리렌더링 될 때마다 실행이 되고, 두번째 인자 리스트 요소에 해당하는 값에 변경이 있으면 함수를 재실행하는 것으로 알고 있습니다. useEffect없이 `stateRef.current = state;`를 함수 내부에 선언만 해도 똑같은 효과가 있다고 생각해서 useEffect를 지웠는데 의도하신 부분이 맞을까요?

2022-04-25 16:20 UTC, kamwoo commented on src/components/Calculator.js
> +  }, []);
변수 선언을 먼저하고 사용하는게 가독성에 더 좋아서 말씀하신게 아닐까 생각했고 수정했습니다.

2022-04-25 16:37 UTC, kamwoo commented on src/components/AllClearButton.js
> +    setState(CALCULATOR_INITIAL_STATE);
넵! props 이름이랑 넘기는 이름과 최대한 비슷하게 지어야 한다고만 생각했었습니다. 사용하는 곳에서 관점으로도 생각해봐야겠다고 느꼈습니다.

2022-04-25 16:56 UTC, kamwoo commented on src/components/OperatorButton.js
> +  };
다시 보니깐 operator 버튼에서 계산을 하는게 이상하네요! 말씀하신대로 calculator에서 '='을 눌렀을 때 처리하는 것으로 수정했습니다.

2022-04-25 23:12 UTC, HyeonaKwon commented on src/components/Calculator.js
> +  });
**useEffect없이 stateRef.current = state;를 함수 내부에 선언만 해도 똑같은 효과가 있다**

useEffect 와 ref 는 다른 기능입니다! 특히 ref 와 리렌더링은 관련이 없는데요, 요 부분 다시 공부해보시면 좋을 것 같네요!
리액트 컴포넌트는 상태가 바뀔 때마다 리렌더링이 일어나는데 밧드 코드는 반대로 리렌더링이 일어날 때마다 상태가 바꾸고 있습니다. 이건 ref 이기 때문에 가능하겠죠?
stateRef 는 지워도 될 것 같네요!

그리고 useState 로 상태를 저장하고 있는데 stateRef 로 이중 상태를 관리하고 있는 이유가 궁금하네요!

2022-04-25 23:16 UTC, HyeonaKwon requested changes
밧드 수정사항 확인했습니다! :)
다시 코멘트 남긴 부분 확인 부탁드리고, state / setState / prevState 는 말씀드린 코드 뿐만 아니라 전체적으로 확인해보면 좋을 것 같아요!

2022-04-26 03:02 UTC, kamwoo commented on src/components/Calculator.js
> +  });
> useState 로 상태를 저장하고 있는데 stateRef 로 이중 상태를 관리하고 있는 이유가 궁금하네요!

ref를 사용하지 않았을 때 로컬 저장소에 초기값만 저장되는 문제가 있었습니다.
정확한 이유를 파악하지 못했지만 버튼이 클릭되고 리렌더링이 되면서 값이 변경되어도 처음에 설정된 초기값이 들어간다고 생각했습니다.
그래서 ref를 사용해서 렌더링이 일어날 때마다 최신값으로 상태를 변경해서 사용했습니다.

2022-04-27 14:44 UTC, HyeonaKwon approved these changes
수정사항 모두 확인했습니다 밧드 :) 모두 적용해주셔서 감사해요!
음 그리고 ref 관련 코드는 없어도 될 것 같아요! 이미 다음 미션이 시작됐으니 나중에 시간되실 때 한번 다시 확인해보셔도 좋을 것 같네요! 시간이 지나면 더 빨리 해결될 때도 있으니까요 🙃
고생 많으셨습니다!

2022-04-27 14:44 UTC, merged