[2단계 - 계산기] 안 (안수진) 미션 제출합니다.
woowacourse/react-calculator pull request #70
Opened 2022-04-25 05:25 UTC by jin7969

안녕하세요. 헤인티님~ 😆
온보딩 미션이라 아쉽네요 ㅠㅠ 다음에 또 만날 수 있게죠? ㅎ
### [데모 페이지](https://jin7969.github.io/react-calculator/)

### ✅ step2 변경사항
- ref를 사용하지 않고, 상태에 따라 결과값을 보여주도록 변경하였습니다.
` <h1 id="calculator-number">{prevNumber ? prevNumber + operation + nextNumber : result}</h1>`

- 연산자에 따라 계산하는 로직을 props로 넘겨주지 않고 swith문에서 바로 수행하도록 변경하였습니다.
```js
let calculationResult;
switch (operation) {
  case '+':
    calculationResult = Number(prevNumber) + Number(nextNumber);
    break;
  case'-':
  ...
```

- Infinity 체크하는 로직을 기존에는 0으로 나누었을때만 해주었지만, 결과값이 Infinity 일 경우 '오류'가 출력 되도록 변경하였습니다.
7f6a6e3fc2264fb9886a4a81e3eb6b57e697d5b5

2022-04-25 15:52 UTC, HyeonaKwon requested changes
안 안녕하세요! 코드가 깔끔해져서 보기 좋네요 👍 
특별한 코멘트는 없구 App / useEffect 관련해서 피드백 주시면 좋을 것 같아요~!

2022-04-25 15:52 UTC, HyeonaKwon commented on react-calculator/package.json
> +      "no-param-reassign": "off",
요거는 꼭 필요했을까 싶네요..!

2022-04-25 15:52 UTC, HyeonaKwon commented on react-calculator/src/App.jsx
> +  });
useEffect 의 두번째 인자에 대해 알아볼까요? 그리고 빈 값을 넘겼을 때는 App이 리렌더링될 때마다 어떻게 실행될까요?

2022-04-25 15:52 UTC, HyeonaKwon commented on react-calculator/src/components/digits.jsx
> +      ))}
👍

2022-04-25 15:52 UTC, HyeonaKwon commented on react-calculator/src/index.js
> +/* eslint-disable comma-dangle */
👀

2022-04-25 15:52 UTC, HyeonaKwon commented on react-calculator/src/App.jsx
>  export default App;
App 은 프로그램이 어떻게 이루어졌는지를 한 눈에 볼 수 있어야해요. 예를 들면 App 에 route 관련 코드를 넣어두고 어떤 url 에 어떤 컴포넌트를 보여줄건지 한눈에 보여주는 것과 같이요!
지금 안의 코드는 App 에서 모든 비즈니스 로직을 관리하고 있어서 사실상 코드를 다 읽어봐야해요. 
App 을 간단하게 하고 나머지는 page 컴포넌트 또는 도메인 컴포넌트(예를 들면 Calculator)로 바꿔볼까요?

2022-04-26 16:29 UTC, jin7969 commented on react-calculator/package.json
> +      "no-param-reassign": "off",
오류가 생겨서 설정을 하고 삭제를 안해주었네요 ㅠㅠ 수정하겠습니다!

2022-04-26 16:42 UTC, jin7969 commented on react-calculator/src/index.js
> +/* eslint-disable comma-dangle */
`prettier.trailingComma (default: 'none')` default 값이 none 이므로 index.js 파일을 저장하였을때 콤마가 자동으로 삭제되어서 eslint에서 오류가 납니다. 그래서 prettierrc.json 에서 설정을 추가하기 보단  `eslint-disable comma-dangle`을 사용하여 오류를 제거 하였고, 파일 전체에 막기보단 밑에 한줄만 적용하면 되므로 아래와 같이 수정하였습니다.
```js
  <React.StrictMode>
    <App />
    {/* eslint-disable-next-line comma-dangle */}
  </React.StrictMode>
``` 
제가 이해한게 맞을까요??

2022-04-26 17:00 UTC, jin7969 commented on react-calculator/src/App.jsx
>  export default App;
애플리케이션이 커지면 App 에서 한 눈에 확인 하는것이 좋겠군요!! 
calculate 컴포넌트로 분리하였습니다~
https://github.com/woowacourse/react-calculator/pull/70/commits/d0dc706da522af6f44eae9034f47f5f072869c88

> 헤인티님은 컴포넌트 파일명을 어떻게 하시나요?
1. calculate.jsx - 소문자
2. Calculate.jsx - 대문자

대문자로 하게되면 `Reactjs code snippets` 익스텐션을 사용할때 대문자로 따로 변경을 안해줘서 편하긴 하지만,
파일명을 굳이 대문자로 할 이유가 있나? 생각이 들어서 질문드립니다.

2022-04-26 17:17 UTC, jin7969 commented on react-calculator/src/App.jsx
> +  });
첫째 인자는 변경시 호출할 콜백함수고 두번째 인자는 상태 변경을 감지할 state를 설정합니다.
- 빈 값( ): 마운트될때, state가 변경될때 계속 호출된다
- 빈 배열: 최초 한번만 호출 된다 = componentDidMount
- [상태값]: 입력한 상태값이 변경 될떄 마다 호출된다

따라서, unload 할 때만 필요하므로 `빈 배열[]`로 설정하였습니다.

2022-04-27 07:23 UTC, HyeonaKwon commented on react-calculator/src/index.js
> +/* eslint-disable comma-dangle */
아하 린트무시를 하는 것보다 프리티어 config 파일을 추가하면 어땠을까 하는 생각이 드네요!

2022-04-27 07:25 UTC, HyeonaKwon commented on react-calculator/src/App.jsx
>  export default App;
컴포넌트는 대문자인게 맞을 것 같아요! 저는 파일명에 소문자 쓰는 경우는 상수, 로직과 관련된 함수, 유틸 함수 등 실제로 밖에서도 소문자로 사용하면서 안에 클래스나 인터페이스가 아닌 변수같은 것들이 들어있구나! 를 알 수 있도록 할 때 소문자를 사용하고는 합니다 :)

2022-04-27 07:27 UTC, HyeonaKwon approved these changes
수정사항 모두 확인했습니다! 아직은 간단한 온보딩 미션이라 App 이 너무 간단한거 아닌가..? 싶을 수도 있지만 앞으로의 미션을 수행해나가다보면 App 을 보고 파악한다는게 어떤 의미인지 알 수 있을거에요!

첫 리액트 미션 수행하느라 고생 많으셨습니다! 👍

2022-04-27 07:27 UTC, merged